/**
 *
 * $Id$
 */
package patterns.validation;


/**
 * A sample validator interface for {@link patterns.Preservation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PreservationValidator {
	boolean validate();

	boolean validateMeasure(String value);
	boolean validateValue1(double value);
	boolean validateValue2(double value);
}
