/**
 *
 * $Id$
 */
package patterns.validation;

import org.eclipse.emf.common.util.EList;

import patterns.Location;

/**
 * A sample validator interface for {@link patterns.SpecificationPatterns}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SpecificationPatternsValidator {
	boolean validate();

	boolean validateLocations(EList<Location> value);
	boolean validateType(String value);
}
