/**
 * generated by Xtext 2.28.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Composite Patterns</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCompositePatterns()
 * @model
 * @generated
 */
public interface CompositePatterns extends Missions
{
} // CompositePatterns
