/**
 * generated by Xtext 2.28.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Complex Missions</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ComplexMissions#getComposition <em>Composition</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getComplexMissions()
 * @model
 * @generated
 */
public interface ComplexMissions extends Missions
{
  /**
   * Returns the value of the '<em><b>Composition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Composition</em>' containment reference.
   * @see #setComposition(MissionOperation)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getComplexMissions_Composition()
   * @model containment="true"
   * @generated
   */
  MissionOperation getComposition();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ComplexMissions#getComposition <em>Composition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Composition</em>' containment reference.
   * @see #getComposition()
   * @generated
   */
  void setComposition(MissionOperation value);

} // ComplexMissions
