/**
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Equidistance</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Equidistance#getRobots <em>Robots</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Equidistance#getMissions <em>Missions</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Equidistance#getRobots1 <em>Robots1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Equidistance#getRobots2 <em>Robots2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEquidistance()
 * @model
 * @generated
 */
public interface Equidistance extends CompositePatterns
{
  /**
   * Returns the value of the '<em><b>Robots</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Robots</em>' reference.
   * @see #setRobots(Robots)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEquidistance_Robots()
   * @model
   * @generated
   */
  Robots getRobots();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Equidistance#getRobots <em>Robots</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Robots</em>' reference.
   * @see #getRobots()
   * @generated
   */
  void setRobots(Robots value);

  /**
   * Returns the value of the '<em><b>Missions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Missions</em>' containment reference.
   * @see #setMissions(Missions)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEquidistance_Missions()
   * @model containment="true"
   * @generated
   */
  Missions getMissions();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Equidistance#getMissions <em>Missions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Missions</em>' containment reference.
   * @see #getMissions()
   * @generated
   */
  void setMissions(Missions value);

  /**
   * Returns the value of the '<em><b>Robots1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Robots1</em>' reference.
   * @see #setRobots1(Robots)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEquidistance_Robots1()
   * @model
   * @generated
   */
  Robots getRobots1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Equidistance#getRobots1 <em>Robots1</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Robots1</em>' reference.
   * @see #getRobots1()
   * @generated
   */
  void setRobots1(Robots value);

  /**
   * Returns the value of the '<em><b>Robots2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Robots2</em>' reference.
   * @see #setRobots2(Robots)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEquidistance_Robots2()
   * @model
   * @generated
   */
  Robots getRobots2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Equidistance#getRobots2 <em>Robots2</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Robots2</em>' reference.
   * @see #getRobots2()
   * @generated
   */
  void setRobots2(Robots value);

} // Equidistance
