/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Shall Missions</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ShallMissions#getRobots <em>Robots</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ShallMissions#getMovementPatterns <em>Movement Patterns</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getShallMissions()
 * @model
 * @generated
 */
public interface ShallMissions extends Missions
{
  /**
   * Returns the value of the '<em><b>Robots</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Robots</em>' reference.
   * @see #setRobots(Robots)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getShallMissions_Robots()
   * @model
   * @generated
   */
  Robots getRobots();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ShallMissions#getRobots <em>Robots</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Robots</em>' reference.
   * @see #getRobots()
   * @generated
   */
  void setRobots(Robots value);

  /**
   * Returns the value of the '<em><b>Movement Patterns</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Movement Patterns</em>' containment reference.
   * @see #setMovementPatterns(SpecificationPatterns)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getShallMissions_MovementPatterns()
   * @model containment="true"
   * @generated
   */
  SpecificationPatterns getMovementPatterns();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ShallMissions#getMovementPatterns <em>Movement Patterns</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Movement Patterns</em>' containment reference.
   * @see #getMovementPatterns()
   * @generated
   */
  void setMovementPatterns(SpecificationPatterns value);

} // ShallMissions
