/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Within</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Within#getValue1 <em>Value1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Within#getValue2 <em>Value2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getWithin()
 * @model
 * @generated
 */
public interface Within extends ElementaryPatterns
{
  /**
   * Returns the value of the '<em><b>Value1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value1</em>' attribute.
   * @see #setValue1(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getWithin_Value1()
   * @model
   * @generated
   */
  int getValue1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Within#getValue1 <em>Value1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value1</em>' attribute.
   * @see #getValue1()
   * @generated
   */
  void setValue1(int value);

  /**
   * Returns the value of the '<em><b>Value2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value2</em>' attribute.
   * @see #setValue2(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getWithin_Value2()
   * @model
   * @generated
   */
  int getValue2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Within#getValue2 <em>Value2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value2</em>' attribute.
   * @see #getValue2()
   * @generated
   */
  void setValue2(int value);

} // Within
